server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8811/oauth2server?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}  # modify username
    password: ${MYSQL_PASSWORD:root}  # modify password
  flyway:
    baseline-on-migrate: true
    baseline-description: <<Flyway Baseline>>
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    fail-on-missing-locations: true
#  security:
#    oauth2:
#      authorizationserver:
#        relive-messaging-oidc:
#          registration:
#            client-id: relive-client
#            client-secret: "{noop}relive-client"
#            client-authentication-methods:
#              - "client_secret_basic"
#              - "client_secret_post"
#            authorization-grant-types:
#              - "authorization_code"
#              - "refresh_token"
#            redirect-uris:
#              - "http://127.0.0.1:8070/login/oauth2/code/messaging-gateway-oidc"
#            scope:
#              - profile
#              - email
#              - openid
#              - read
#          require-authorization-consent: true
#          require-proof-key: true

#logging:
#  level:
#    root: ERROR
#    org.springframework.web: ERROR
#    org.springframework.security: ERROR
#    org.springframework.security.oauth2: ERROR
#    org.springframework.cloud.gateway: ERROR